dofile(libpath .. "net/net.mobile.lua")
dofile(libpath .. "net/net.dynamic.lua")
dofile(libpath .. "net/net.object.lua")
dofile(libpath .. "net/net.effect.lua")
dofile(libpath .. "net/net.multi.lua")
dofile(libpath .. "net/net.partysystem.lua")
dofile(libpath .. "net/net.uodragdrop.lua")
dofile(libpath .. "net/net.corpse.lua")
dofile(libpath .. "net/net.world.lua")
dofile(libpath .. "net/net.sound.lua")
dofile(libpath .. "net/net.login.lua")
dofile(libpath .. "net/net.skill.lua")
dofile(libpath .. "net/net.buff.lua")
dofile(libpath .. "net/net.aoscommand.lua")
dofile(libpath .. "net/net.cursor.lua")
dofile(libpath .. "net/net.other.lua")
dofile(libpath .. "net/net.text.lua")
dofile(libpath .. "net/net.generic.lua")
dofile(libpath .. "net/net.gump.lua")
dofile(libpath .. "net/net.extended.lua")
dofile(libpath .. "net/net.securetrade.lua")
dofile(libpath .. "net/net.trade.lua")
dofile(libpath .. "net/net.uoam.lua")
dofile(libpath .. "net/net.walk.lua")
dofile(libpath .. "net/net.book.lua")
dofile(libpath .. "net/net.huepicker.lua")
dofile(libpath .. "net/net.objectpicker.lua")
dofile(libpath .. "net/net.tooltips.lua")

-- only things that have at least 2 packets get its own file, everything else is handled here:
dofile(libpath .. "net/net.packethandlers.lua")

gLastDoubleClickSerial = 0

