-- DO NOT EDIT THIS FILE DIRECTLY, or your changes might be lost when using the updater.
-- DO NOT EDIT THIS FILE DIRECTLY, create a new file mymacros.lua to make individual configurations outside version management
-- DO NOT EDIT THIS FILE DIRECTLY, you can override individual settings there.
--[[
Here you can define macros, 
which can be triggered by keycombos like ctrl-shift-a or similar.
See http://www.iris2.de/index.php/Macros for more infos.

Use qwerty key to make Macros!
]]--

-- uncomment this line to print the current keyname on each keypress :
-- gMacroPrintAllKeyCombos = true

-- uncomment this line to clear all preset macros
-- ClearAllMacros()

SetMacro("ctrl+s",	function() MacroCmd_Open("Status") end)	-- Open Status window
SetMacro("alt+c",	function() MacroCmd_ToggleWarmode() end)	-- Toggle between War/Peace modes
SetMacro("alt+p",	function() MacroCmd_Open("Paperdoll") end)	-- Open Character Window
SetMacro("alt+k",	function() MacroCmd_Open("Skill") end)	-- Open Skills
SetMacro("alt+j",	function() MacroCmd_Open("Journal") end)	-- Open Journal
SetMacro("alt+i",	function() MacroCmd_Open("Backpack") end)	-- Open Backpack
SetMacro("alt+x",	function() OpenQuit() end)	-- Quit game
SetMacro("alt+b",	function() MacroCmd_Say("*bow*") end)	-- Bow
SetMacro("alt+s",	function() MacroCmd_Say("*salute*") end)	-- Salute

SetMacro("j",		function() MacroCmd_Open("Journal") end)	-- Open Journal
SetMacro("b",		function() MacroCmd_Open("Backpack") end)	-- Open Backpack
SetMacro("p",		function() MacroCmd_Open("Paperdoll") end)	-- Open Character Window
SetMacro("alt+l",	function() MacroCmd_Open("PartyList") end)	
SetMacro("t",		function() MacroCmd_Open("Status") end)	-- Open Status window
SetMacro("k",		function() MacroCmd_Open("Skill") end)	-- Open Skills
SetMacro("c",		function() MacroCmd_NextCamMode() end)	-- change cam mode

--common
SetMacro("l",			function() MacroCmd_Open("Logo") end)
SetMacro("n",			function() MacroCmd_Open("Compass") end)
SetMacro("tab",			function() MacroCmd_ToggleWarmode() end)
SetMacro("komma",		function() MacroCmd_ZoomCompass(1*1.5) end)
SetMacro("point",		function() MacroCmd_ZoomCompass(1/1.5) end)
SetMacro("f12",			function() FadeLineToggleShowAll() end)

--cam control
SetMacro("x",			function() MacroCmd_CamChangeZoom( 1) end)
SetMacro("y",			function() MacroCmd_CamChangeZoom(-1) end)
SetMacro("wheelup",		function() MacroCmd_CamChangeZoom(-0.3) end)
SetMacro("wheeldown",	function() MacroCmd_CamChangeZoom( 0.3) end)

-- screenshots
SetMacro("v",			function() MacroCmd_Screenshot() end)
SetMacro("alt+v",		function() MacroCmd_ToggleHideGUI() MacroCmd_Screenshot() MacroCmd_ToggleHideGUI() end)
SetMacro("shift+f12",	function() MacroCmd_GridScreenshot() end)

SetMacro("g",			function() MacroCmd_RepeatLastChat() end)
SetMacro("h",			function() MacroCmd_RepeatLastDoubleClick() end)
SetMacro("q",			function() MacroCmd_SelectNearestMobile() end)
SetMacro("e",			function() MacroCmd_SelectNextMobile() end)
SetMacro("ctrl+r",			function() MacroCmd_ActivateNextRenderer() end)

--associate Item Slots
SetMacro("ctrl+f1",		function() MacroCmd_ItemSlot_Set(1) end)
SetMacro("ctrl+f2",		function() MacroCmd_ItemSlot_Set(2) end)
SetMacro("ctrl+f3",		function() MacroCmd_ItemSlot_Set(3) end)
SetMacro("ctrl+f4",		function() MacroCmd_ItemSlot_Set(4) end)

--use Item Slots
SetMacro("f1",			function() MacroCmd_ItemSlot_Use(1) end)
SetMacro("f2",			function() MacroCmd_ItemSlot_Use(2) end)
SetMacro("f3",			function() MacroCmd_ItemSlot_Use(3) end)
SetMacro("f4",			function() MacroCmd_ItemSlot_Use(4) end)
--special Item Slot
SetMacro("f5",			function() MacroCmd_ItemSlot_Use(1) MacroCmd_TargetLast() end)
SetMacro("f6",			function() MacroCmd_Item_UseByName("clean bandage") MacroCmd_TargetSelf() end)

--developer Tool
SetMacro("f10",			function() MacroCmd_ShowDevTool() end)

-- build commands for RunUO/SunUO and Iris Testshard
SetMacro("pgup",		function() MacroCmd_Say("[xmove 0,0,1") end)
SetMacro("pgdn",		function() MacroCmd_Say("[xmove 0,0,-1") end)
-- INS is defined in lib.keybinds.lua to call the build menu
SetMacro("del",			function() MacroCmd_Say("[remove") end)
SetMacro("home",		function() MacroCmd_Say("[tele") end)
SetMacro("end",			function() MacroCmd_Say("[get z") end)

--Razor config import
SetMacro("shift+f11",	function() ImportRazorProfileDialog() end)
ImportRazorProfile("C:\\Program Files\\Razor\\Profiles\\default.xml") -- import default config

--~ SetMacro("space",		function() MacroCmd_AttackSelectedMobile() end) -- currently broken
--~ SetMacro("f11",			function() MacroCmd_ShowFallBackTool() end) -- currently broken

--[[
--old uo pre-set default :  (not yet implemented in iris)
--~ SetMacro("ctrl+h",	function() MacroCmd_Spell("Heal") end)
--~ SetMacro("ctrl+a",	function() MacroCmd_Skill("Anatomy") end)
--~ SetMacro("alt+b",function() MacroCmd_Open("Spellbook") end) -- Open Spellbook -- not yet implemented
--~ SetMacro("alt+r",function() MacroCmd_Open("") end)  -- Open Overhead View -- not yet implemented
--~ SetMacro("alt+o",function() MacroCmd_Open("") end)  -- Open Options window -- not yet implemented
]]--

--[[
SetMacro("F1",	function() MacroCmd_Item_UseByArtID(3852) end)	-- greater health
SetMacro("F2",	function() MacroCmd_Item_UseByArtID(3847) end)	-- greater cure
SetMacro("F3",	function() MacroCmd_Item_UseByArtID(3851) end)	-- total refresh
SetMacro("F4",	function() if (MacroCmd_LastTargetVisible() and MacroCmd_Item_UseByArtID(10229)) then MacroCmd_TargetLast(nil,1000) end end) -- fukija
SetMacro("F4",	function() if (MacroCmd_LastTargetVisible() and MacroCmd_Item_UseByArtID(3853)) then MacroCmd_TargetLast(nil,1000) end end) -- explo pot

SetMacro("alt+a",	function() MacroCmd_Skill("Spirit Speak") end)
SetMacro("alt+s",	function() MacroCmd_Spell("Greater Heal") end)
SetMacro("alt+d",	function() MacroCmd_Spell("Arch Cure") end)
SetMacro("alt+1",	function() MacroCmd_Spell("Magic Arrow") end)
SetMacro("alt+2",	function() MacroCmd_Spell("Fire Ball") end)
SetMacro("alt+3",	function() MacroCmd_Spell("FlameStrike") end)
SetMacro("alt+4",	function() MacroCmd_Spell("Energy Bolt") end)
SetMacro("alt+C",	function() MacroCmd_Spell("Wither") end)
SetMacro("alt+T",	function() MacroCmd_Spell("Teleport") end)
SetMacro("alt+Z",	function() MacroCmd_Spell("Invisibility") end)
SetMacro("alt+X",	function() MacroCmd_Spell("Meteor Swarm") end)
]]--
